CREATE TABLE foundation
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer VARCHAR(255) NOT NULL,
    created  TIMESTAMP(3) NOT NULL,
    updated  TIMESTAMP(3) NOT NULL,
    deleted  BOOLEAN      NOT NULL,
    name     VARCHAR(255) NOT NULL
);

CREATE TABLE examiner
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer        VARCHAR(255) NOT NULL,
    created         TIMESTAMP(3) NOT NULL,
    updated         TIMESTAMP(3) NOT NULL,
    deleted         BOOLEAN      NOT NULL,
    name            VARCHAR(255) NOT NULL,
    mail            VARCHAR(255) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    blocked         BOOLEAN      NOT NULL,
    last_login_date TIMESTAMP(3)
);

CREATE TABLE student_group
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer VARCHAR(255) NOT NULL,
    created  TIMESTAMP(3) NOT NULL,
    updated  TIMESTAMP(3) NOT NULL,
    deleted  BOOLEAN      NOT NULL,
    name     VARCHAR(255) NOT NULL
);

CREATE TABLE student
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer        VARCHAR(255) NOT NULL,
    created         TIMESTAMP(3) NOT NULL,
    updated         TIMESTAMP(3) NOT NULL,
    deleted         BOOLEAN      NOT NULL,
    number          VARCHAR(255),
    group_id        BIGINT,
    name            VARCHAR(255) NOT NULL,
    mail            VARCHAR(255) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    blocked         BOOLEAN      NOT NULL,
    last_login_date TIMESTAMP(3)
);

ALTER TABLE student
    ADD CONSTRAINT FK_STUDENT_GROUP_ID FOREIGN KEY (group_id) REFERENCES student_group (id);

CREATE TABLE exam
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer    VARCHAR(255) NOT NULL,
    created     TIMESTAMP(3) NOT NULL,
    updated     TIMESTAMP(3) NOT NULL,
    deleted     BOOLEAN      NOT NULL,
    duration    BIGINT,
    examiner_id BIGINT       NOT NULL,
    start_date  TIMESTAMP(3) NOT NULL,
    end_date    TIMESTAMP(3) NOT NULL
);

ALTER TABLE exam
    ADD CONSTRAINT FK_EXAM_EXAMINER_ID FOREIGN KEY (examiner_id) REFERENCES examiner (id);

CREATE TABLE question
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer             VARCHAR(255) NOT NULL,
    created              TIMESTAMP(3) NOT NULL,
    updated              TIMESTAMP(3) NOT NULL,
    deleted              BOOLEAN      NOT NULL,
    exam_id              BIGINT       NOT NULL,
    text                 VARCHAR(255) NOT NULL,
    answers              VARCHAR(255) NOT NULL,
    correct_answer_index INTEGER      NOT NULL
);

ALTER TABLE question
    ADD CONSTRAINT FK_QUESTION_EXAM_ID FOREIGN KEY (exam_id) REFERENCES exam (id);

CREATE TABLE exam_result
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer   VARCHAR(255)     NOT NULL,
    created    TIMESTAMP(3)     NOT NULL,
    updated    TIMESTAMP(3)     NOT NULL,
    deleted    BOOLEAN          NOT NULL,
    exam_id    BIGINT           NOT NULL,
    student_id BIGINT           NOT NULL,
    answers    VARCHAR(255)     NOT NULL,
    score      DOUBLE PRECISION NOT NULL,
    login_date TIMESTAMP(3)     NOT NULL
);

ALTER TABLE exam_result
    ADD CONSTRAINT FK_EXAM_RESULT_EXAM_ID FOREIGN KEY (exam_id) REFERENCES exam (id);

ALTER TABLE exam_result
    ADD CONSTRAINT FK_EXAM_RESULT_STUDENT_ID FOREIGN KEY (student_id) REFERENCES student (id);


CREATE TABLE student_groups
(
    student_id BIGINT NOT NULL,
    group_id   BIGINT NOT NULL
);

ALTER TABLE student_groups
    ADD CONSTRAINT FK_STUDENT_GROUPS_STUDENT_ID FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE student_groups
    ADD CONSTRAINT FK_STUDENT_GROUPS_GROUP_ID FOREIGN KEY (group_id) REFERENCES student_group (id);

CREATE TABLE student_results
(
    student_id     BIGINT NOT NULL,
    exam_result_id BIGINT NOT NULL
);

ALTER TABLE student_results
    ADD CONSTRAINT FK_STUDENT_RESULTS_STUDENT_ID FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE student_results
    ADD CONSTRAINT FK_STUDENT_RESULTS_EXAM_RESULT_ID FOREIGN KEY (exam_result_id) REFERENCES exam_result (id);

CREATE TABLE examiner_exams
(
    examiner_id BIGINT NOT NULL,
    exam_id     BIGINT NOT NULL
);

ALTER TABLE examiner_exams
    ADD CONSTRAINT FK_EXAMINER_EXAMS_EXAMINER_ID FOREIGN KEY (examiner_id) REFERENCES examiner (id);

ALTER TABLE examiner_exams
    ADD CONSTRAINT FK_EXAMINER_EXAMS_EXAM_ID FOREIGN KEY (exam_id) REFERENCES exam (id);

CREATE TABLE exam_students
(
    student_id BIGINT NOT NULL,
    exam_id    BIGINT NOT NULL
);

ALTER TABLE exam_students
    ADD CONSTRAINT FK_EXAM_STUDENTS_STUDENT_ID FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE exam_students
    ADD CONSTRAINT FK_EXAM_STUDENTS_EXAM_ID FOREIGN KEY (exam_id) REFERENCES exam (id);

CREATE TABLE exam_questions
(
    exam_id     BIGINT NOT NULL,
    question_id BIGINT NOT NULL
);

ALTER TABLE exam_questions
    ADD CONSTRAINT FK_EXAM_QUESTIONS_EXAM_ID FOREIGN KEY (exam_id) REFERENCES exam (id);

ALTER TABLE exam_questions
    ADD CONSTRAINT FK_EXAM_QUESTIONS_QUESTION_ID FOREIGN KEY (question_id) REFERENCES question (id);

CREATE TABLE foundation_managers
(
    foundation_id BIGINT NOT NULL,
    manager_id    BIGINT NOT NULL
);

ALTER TABLE foundation_managers
    ADD CONSTRAINT FK_FOUNDATION_MANAGERS_FOUNDATION_ID FOREIGN KEY (foundation_id) REFERENCES foundation (id);

ALTER TABLE foundation_managers
    ADD CONSTRAINT FK_FOUNDATION_MANAGERS_MANAGER_ID FOREIGN KEY (manager_id) REFERENCES examiner (id);

CREATE TABLE foundation_examiners
(
    foundation_id BIGINT NOT NULL,
    examiner_id   BIGINT NOT NULL
);

ALTER TABLE foundation_examiners
    ADD CONSTRAINT FK_FOUNDATION_EXAMINERS_FOUNDATION_ID FOREIGN KEY (foundation_id) REFERENCES foundation (id);

ALTER TABLE foundation_examiners
    ADD CONSTRAINT FK_FOUNDATION_EXAMINERS_EXAMINER_ID FOREIGN KEY (examiner_id) REFERENCES examiner (id);

CREATE TABLE foundation_student
(
    foundation_id BIGINT NOT NULL,
    student_id    BIGINT NOT NULL
);

ALTER TABLE foundation_student
    ADD CONSTRAINT FK_FOUNDATION_STUDENT_FOUNDATION_ID FOREIGN KEY (foundation_id) REFERENCES foundation (id);

ALTER TABLE foundation_student
    ADD CONSTRAINT FK_FOUNDATION_STUDENT_STUDENT_ID FOREIGN KEY (student_id) REFERENCES student (id);

CREATE TABLE foundation_exams
(
    foundation_id BIGINT NOT NULL,
    exam_id       BIGINT NOT NULL
);

ALTER TABLE foundation_exams
    ADD CONSTRAINT FK_FOUNDATION_EXAMS_FOUNDATION_ID FOREIGN KEY (foundation_id) REFERENCES foundation (id);

ALTER TABLE foundation_exams
    ADD CONSTRAINT FK_FOUNDATION_EXAMS_EXAM_ID FOREIGN KEY (exam_id) REFERENCES student (id);
