CREATE TABLE foundation
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer VARCHAR(255) NOT NULL,
    created  TIMESTAMP(3) NOT NULL,
    updated  TIMESTAMP(3) NOT NULL,
    deleted  BOOLEAN      NOT NULL,
    name     VARCHAR(255) NOT NULL
);

CREATE TABLE student_group
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer VARCHAR(255) NOT NULL,
    created  TIMESTAMP(3) NOT NULL,
    updated  TIMESTAMP(3) NOT NULL,
    deleted  BOOLEAN      NOT NULL,
    name     VARCHAR(255) NOT NULL
);

CREATE TABLE student
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer        VARCHAR(255) NOT NULL,
    created         TIMESTAMP(3) NOT NULL,
    updated         TIMESTAMP(3) NOT NULL,
    deleted         BOOLEAN      NOT NULL,
    number          VARCHAR(255),
    group_id        BIGINT,
    name            VARCHAR(255) NOT NULL,
    mail            VARCHAR(255) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    blocked         BOOLEAN      NOT NULL,
    last_login_date TIMESTAMP(3)
);

ALTER TABLE student
    ADD CONSTRAINT FK_STUDENT_GROUP_ID FOREIGN KEY (group_id) REFERENCES student_group (id);

CREATE TABLE exam
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer    VARCHAR(255) NOT NULL,
    created     TIMESTAMP(3) NOT NULL,
    updated     TIMESTAMP(3) NOT NULL,
    deleted     BOOLEAN      NOT NULL,
    duration    BIGINT,
    start_date  TIMESTAMP(3) NOT NULL,
    end_date    TIMESTAMP(3) NOT NULL
);

CREATE TABLE question
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer             VARCHAR(255) NOT NULL,
    created              TIMESTAMP(3) NOT NULL,
    updated              TIMESTAMP(3) NOT NULL,
    deleted              BOOLEAN      NOT NULL,
    exam_id              BIGINT       NOT NULL,
    text                 VARCHAR(255) NOT NULL,
    answers              VARCHAR(255) NOT NULL,
    correct_answer_index INTEGER      NOT NULL
);

ALTER TABLE question
    ADD CONSTRAINT FK_QUESTION_EXAM_ID FOREIGN KEY (exam_id) REFERENCES exam (id);

CREATE TABLE exam_login
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer   VARCHAR(255)     NOT NULL,
    created    TIMESTAMP(3)     NOT NULL,
    updated    TIMESTAMP(3)     NOT NULL,
    deleted    BOOLEAN          NOT NULL,
    exam_id    BIGINT           NOT NULL,
    student_id BIGINT           NOT NULL,
    answers    VARCHAR(255)     NOT NULL,
    score      DOUBLE PRECISION NOT NULL,
    login_date TIMESTAMP(3)     NOT NULL,
    duration    BIGINT
);

ALTER TABLE exam_login
    ADD CONSTRAINT FK_EXAM_LOGIN_EXAM_ID FOREIGN KEY (exam_id) REFERENCES exam (id);

ALTER TABLE exam_login
    ADD CONSTRAINT FK_EXAM_LOGIN_STUDENT_ID FOREIGN KEY (student_id) REFERENCES student (id);


CREATE TABLE student_groups
(
    student_id BIGINT NOT NULL,
    group_id   BIGINT NOT NULL
);

ALTER TABLE student_groups
    ADD CONSTRAINT FK_STUDENT_GROUPS_STUDENT_ID FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE student_groups
    ADD CONSTRAINT FK_STUDENT_GROUPS_GROUP_ID FOREIGN KEY (group_id) REFERENCES student_group (id);

CREATE TABLE exam_students
(
    student_id BIGINT NOT NULL,
    exam_id    BIGINT NOT NULL
);

ALTER TABLE exam_students
    ADD CONSTRAINT FK_EXAM_STUDENTS_STUDENT_ID FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE exam_students
    ADD CONSTRAINT FK_EXAM_STUDENTS_EXAM_ID FOREIGN KEY (exam_id) REFERENCES exam (id);

CREATE TABLE foundation_student
(
    foundation_id BIGINT NOT NULL,
    student_id    BIGINT NOT NULL
);

ALTER TABLE foundation_student
    ADD CONSTRAINT FK_FOUNDATION_STUDENT_FOUNDATION_ID FOREIGN KEY (foundation_id) REFERENCES foundation (id);

ALTER TABLE foundation_student
    ADD CONSTRAINT FK_FOUNDATION_STUDENT_STUDENT_ID FOREIGN KEY (student_id) REFERENCES student (id);

CREATE TABLE foundation_exams
(
    foundation_id BIGINT NOT NULL,
    exam_id       BIGINT NOT NULL
);

ALTER TABLE foundation_exams
    ADD CONSTRAINT FK_FOUNDATION_EXAMS_FOUNDATION_ID FOREIGN KEY (foundation_id) REFERENCES foundation (id);

ALTER TABLE foundation_exams
    ADD CONSTRAINT FK_FOUNDATION_EXAMS_EXAM_ID FOREIGN KEY (exam_id) REFERENCES student (id);
